// Shader written by Enchanted_Games (https://enchanted.games)
// Please don't steal this code and use it without asking me first
// Any functions not made by me will include a credit line at the top of them

// Generated by https://outlines.enchanted.games

//    -- CONFIG STARTS HERE --
//         !! WARNING !!
//     Do not copy config from
//     an older version of this
//   pack, it will probably crash!

const vec4 block_COLOURS[] = vec4[](
	vec4(1, 0.48627, 0.46667, 1),
	vec4(1, 0.97255, 0.46667, 1),
	vec4(0.5098, 1, 0.46275, 1),
	vec4(0.46667, 0.97255, 1, 1),
	vec4(0.51373, 0.46667, 1, 1),
	vec4(1, 0.46275, 0.89412, 1)
);
#define block_ANIM_SPEED 2000
#define block_COLOUR_PERIOD 7
#define block_SMOOTH_MIX true
#define block_ANIMATE_WITH_DISTANCE true
#define block_ANIMATE_ALONG_LINES false
#define block_ANIM_DIRECTION 1
#define block_LINE_THICKNESS 2

const vec4 hitbox_COLOURS[] = vec4[](
	vec4(1, 0.21961, 0.19216, 1),
	vec4(1, 0.96078, 0.19216, 1),
	vec4(0.25882, 1, 0.19216, 1),
	vec4(0.2, 0.96078, 1, 1),
	vec4(0.25098, 0.18431, 1, 1),
	vec4(1, 0.18824, 0.83922, 1)
);
#define hitbox_ANIM_SPEED 1700
#define hitbox_COLOUR_PERIOD 10
#define hitbox_SMOOTH_MIX true
#define hitbox_ANIMATE_WITH_DISTANCE true
#define hitbox_ANIMATE_ALONG_LINES false
#define hitbox_ANIM_DIRECTION -1
#define hitbox_LINE_THICKNESS 2
#define hitbox_APPLY_TO_ALL_LINES false